spring:
  profiles: common

tencent:
  cloud:
    appId: 1311084610
    secretId: AKIDta3FH5k8F5ey1oLccLmytkPozuZy83i9
    secretKey: DArITP5WhbFciY7QTLxIRSGpCMIzRedN
    region-public: na-ashburn
    bucket-public: hxds-public-1311084610
    region-private: na-ashburn
    bucket-private: hxds-private2-1311084610
    face:
      groupName: driver
      region: ap-shanghai
  map:
    key: YPTBZ-AHFCX-STD43-7OH2T-S3HOS-XIBES

wx:
  app-id: wx47124ed2be667cef
  app-secret: e00977dfab8c1c300fa2ae0892f2a1df
  mch-id: 1526972031
  key: qv9Kihy5TOJxGySzFO8pd4wCMg3tn6YK
  cert-path: D:/apiclient_cert.p12

minio:
  endpoint: http://localhost:9000
  access-key: root
  secret-key: abc123456

